apiVersion: v1
kind: Service
metadata:
  name: chisa-taki-svc
spec:
  selector:
    app: chisa-taki-app
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chisa-taki-deploy
spec:
  selector:
    matchLabels:
      app: chisa-taki-app
  template:
    metadata:
      labels:
        app: chisa-taki-app
    spec:
      containers:
      - name: wiremock
        image: wiremock/wiremock:3.10.0-1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: mappings
          mountPath: /home/wiremock/mappings
          readOnly: true
        - name: files
          mountPath: /home/wiremock/__files
          readOnly: true
      volumes:
      - name: mappings
        configMap:
          name: chisa-taki-config
          items:
          - key: "takina.mappings"
            path: "takina.json"
          - key: "chisato.mappings"
            path: "chisato.json"
      - name: files
        configMap:
          name: chisa-taki-config
          items:
          - key: "chisato.files"
            path: "chisato.json"
