name: Continuous integrations of some packages

on:
  pull_request:
    branches:
      - master
    paths:
      - x-days-anniversary/**
      - .github/workflows/ci.yml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - '3.9'
          - '3,10'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install pytest pytest-randomly
      - name: Run tests for x-days-anniversary
        run: |
          cd x-days-anniversary/
          pytest -vv
